services:
  postgres:
    image: postgres:17
    container_name: elo-arena-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - elo_arena_postgres_data:/var/lib/postgresql/data

volumes:
  elo_arena_postgres_data: